sudo: required
services: docker
language: c
before_install:
  # env vars GOOGLEUSER GOOGLEPASSWORD GOAUTHCID GOAUTHCS
- openssl aes-256-cbc -K $encrypted_089d332adc0c_key -iv $encrypted_089d332adc0c_iv
  -in secret-emp-pl-site.enc -out secret-emp-pl-site -d
- unset CC
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- cd $TRAVIS_BUILD_DIR
install:
- cp emp-pl-site_dev_env.sample emp-pl-site_dev_env
- cat secret-emp-pl-site >> emp-pl-site_dev_env
- cp postgres_dev_env.sample postgres_dev_env
- export PGPASS=$(head -c 20 /dev/urandom | sha1sum|head -c 40)
- echo POSTGRES_PASSWORD=$PGPASS >> postgres_dev_env
- echo PGPASS=$PGPASS >> emp-pl-site_dev_env
- stack docker pull
- docker-compose up -d postgres
- bash dev-certs/genkey.sh
- stack build --test --no-run-tests
- docker-compose up -d selenium
script:
- stack --no-terminal --install-ghc test
jobs:
  include:
    - stage: Build snapshot deps
      install:
        - mkdir -p ~/.local/bin
        - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
          --strip-components=1 -C ~/.local/bin '*/stack'
        - stack docker pull
        # This needs to exist for Stack to launch Docker, but it won't actually
        # read any of the variables so we just make a blank one.
        - touch emp-pl-site_dev_env
        - stack build --only-snapshot
      script: true
    - stage: Test
cache:
  directories:
    - $HOME/.stack/snapshots
