version: '2'
services:
  emp-pl-site:
    image: emp-pl-site-emp-pl-site
    expose: [3000]
    links:
     - postgres
    env_file:
       emp-pl-site_dev_env
  postgres:
    image: postgres:9.5
    env_file: postgres_dev_env
    volumes:
      - ./config/inittestdb.sql:/docker-entrypoint-initdb.d/inittestdb.sql
  nginx:
    image: nginx
    ports:
      - "3443:443"
    links: [emp-pl-site]
    volumes:
      - ./dev-certs:/certs
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  selenium:
    image: selenium/standalone-firefox:local
    ports:
      - "5900:5900"
