version: '2'
services:
  emp-pl-site:
    image: emp-pl-site-emp-pl-site
    expose: [3000]
    links:
     - postgres
    env_file:
       emp-pl-site_dev_env
  postgres:
    image: postgres:9.5
    env_file: postgres_dev_env
    volumes:
      - ./config/inittestdb.sql:/docker-entrypoint-initdb.d/inittestdb.sql
    ports: ["5433:5432"] # For PGAdmin from the host
  nginx:
    image: nginx
    ports:
      - "3443:443"
    links: [emp-pl-site]
    volumes:
      - ./dev-certs:/certs
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  selenium:
    build:
      dockerfile: Dockerfile-selenium
      context: .
    expose: [31337]
    ports:
      - "5900:5900"
