##########
# Postgres
##########
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200G
  storageClassName: standard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:9.5
        name: postgres
        resources: {}
        env:
          - name: POSTGRES_USER
            value: empplsite
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgrespass
                key: pass
          - name: PGDATA
            value: /pgdata/db
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-volume
            mountPath: /pgdata
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: pg-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
###############
# Yesod backend
###############
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yesod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yesod
    spec:
      containers:
      - image: us.gcr.io/emp-pl-site/yesod@sha256:b36ea73f3a9778ea65939bb1c5f93dd7f77377499a3c0a8493a8bcc4c42e449d
        name: yesod
        ports:
          - containerPort: 3000
        env:
          - name: PGHOST
            value: pg-service
          - name: PGDATABASE
            value: empplsite
          - name: PGUSER
            value: empplsite
          - name: APPROOT
            valueFrom:
              configMapKeyRef:
                name: url
                key: root
          - name: PGPASS
            valueFrom:
              secretKeyRef:
                name: postgrespass
                key: pass
          - name: GOAUTHCID
            valueFrom:
              secretKeyRef:
                name: goauth
                key: cid
          - name: GOAUTHCS
            valueFrom:
              secretKeyRef:
                name: goauth
                key: cs
          - name: IP_FROM_HEADER # Use X-Forwarded-For in logs instead of incoming IP.
            value: "true"
          - name: IP_BLOCK_CFG
            value: /etc/config/block-kube.yml
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: ip-block
---
kind: Service
apiVersion: v1
metadata:
  name: yesod-service
spec:
  type: NodePort
  selector:
    app: yesod
  ports:
    - port: 3000
