apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
kind: ConfigMap
apiVersion: v1
data:
  block-kube.yml: |
    # IP blocking for deployment on GKE.
    defaultAllow: false
    trustForwardedFor: true
    routeSpecs:
      # My house
      - range: "67.189.87.218"
        allow: true
      # Load balancer health check. The probes come from 10.100.1.1, but maybe
      # that'll change when I have more than one node?? I really don't
      # understand this. The Google load balancer docs say probes come from
      # a different IP range. I think this is something to do with kube-proxy.
      # https://cloud.google.com/compute/docs/load-balancing/health-checks#https_ssl_proxy_tcp_proxy_and_internal_load_balancing
      - range: "10.0.0.0/8"
        allow: true
metadata:
  name: ip-block
  namespace: dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emp-pl-site
  namespace: dev
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: http-lb-dev
spec:
  tls:
  - hosts:
    - dev.goodcode.cc
    secretName: emp-pl-site-tls
  rules:
  - host: dev.goodcode.cc
    http:
      paths:
      - path: "/*"
        backend:
          serviceName: yesod-service
          servicePort: 3000
---
apiVersion: v1
kind: ConfigMap
data:
  root: "https://dev.goodcode.cc"
metadata:
  name: url
  namespace: dev
