apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
kind: ConfigMap
apiVersion: v1
data:
  block-kube.yml: |
    # IP blocking for deployment on GKE.
    defaultAllow: true
    trustForwardedFor: true
    routeSpecs: []
metadata:
  name: ip-block
  namespace: prod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emp-pl-site
  namespace: prod
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: http-lb-prod
spec:
  tls:
  - hosts:
    - goodcode.cc
    secretName: emp-pl-site-tls
  rules:
  - host: goodcode.cc
    http:
      paths:
      - path: "/*"
        backend:
          serviceName: yesod-service
          servicePort: 3000
---
apiVersion: v1
kind: ConfigMap
data:
  root: "https://goodcode.cc"
metadata:
  name: url
  namespace: prod
