resolver: lts-8.0

packages:
- location:
    git: https://github.com/enolan/async.git
    commit: 9da751d2946da688151cb9861d4fca6baa95c5a6
  extra-dep: true
- location:
    git: https://github.com/enolan/country-codes.git
    commit: 2cfae881a05f375b4a164d6c42e7db61934ba1f3
  extra-dep: true
- location:
    git: https://github.com/enolan/hs-webdriver.git
    commit: 4d9090fcfaf1ae750ec16be174fff7acb365c92d
  extra-dep: true
